In [2]:
import pandas as pd

In [4]:
df = pd.read_csv("MetObjects.csv", low_memory=False)
df.shape

(484956, 54)

In [8]:
df.head ()

,Object Number,Is Highlight,Is Timeline Work,Is Public Domain,Object ID,Gallery Number,Department,AccessionYear,Object Name,Title,...,River,Classification,Rights and Reproduction,Link Resource,Object Wikidata URL,Metadata Date,Repository,Tags,Tags AAT URL,Tags Wikidata URL
0,1979.486.1,False,False,False,1,NaN,The American Wing,1979,Coin,One-dollar Liberty Head Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/1,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
1,1980.264.5,False,False,False,2,NaN,The American Wing,1980,Coin,Ten-dollar Liberty Head Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/2,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
2,67.265.9,False,False,False,3,NaN,The American Wing,1967,Coin,Two-and-a-Half Dollar Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/3,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
3,67.265.10,False,False,False,4,NaN,The American Wing,1967,Coin,Two-and-a-Half Dollar Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/4,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN
4,67.265.11,False,False,False,5,NaN,The American Wing,1967,Coin,Two-and-a-Half Dollar Coin,...,NaN,NaN,NaN,http://www.metmuseum.org/art/collection/search/5,NaN,NaN,"Metropolitan Museum of Art, New York, NY",NaN,NaN,NaN

In [9]:
df.columns

Index(['Object Number', 'Is Highlight', 'Is Timeline Work', 'Is Public Domain',
       'Object ID', 'Gallery Number', 'Department', 'AccessionYear',
       'Object Name', 'Title', 'Culture', 'Period', 'Dynasty', 'Reign',
       'Portfolio', 'Constituent ID', 'Artist Role', 'Artist Prefix',
       'Artist Display Name', 'Artist Display Bio', 'Artist Suffix',
       'Artist Alpha Sort', 'Artist Nationality', 'Artist Begin Date',
       'Artist End Date', 'Artist Gender', 'Artist ULAN URL',
       'Artist Wikidata URL', 'Object Date', 'Object Begin Date',
       'Object End Date', 'Medium', 'Dimensions', 'Credit Line',
       'Geography Type', 'City', 'State', 'County', 'Country', 'Region',
       'Subregion', 'Locale', 'Locus', 'Excavation', 'River', 'Classification',
       'Rights and Reproduction', 'Link Resource', 'Object Wikidata URL',
       'Metadata Date', 'Repository', 'Tags', 'Tags AAT URL',
       'Tags Wikidata URL'],
      dtype='object')

In [10]:
df[["Culture", "Artist Nationality", "Department"]].head()

  Culture Artist Nationality         Department
0     NaN           American  The American Wing
1     NaN           American  The American Wing
2     NaN                NaN  The American Wing
3     NaN                NaN  The American Wing
4     NaN                NaN  The American Wing

In [11]:
df["Culture"].value_counts().head(20)

Culture
American                28579
French                  18435
Greek, Attic            17309
Japan                   16939
China                   13504
Italian                  6526
Japanese                 5990
British                  5476
Roman                    4872
German                   4576
Cypriot                  2904
European                 2669
American or European     2052
Coptic                   1674
French, Paris            1622
Spanish                  1563
British, London          1408
Greek                    1263
Etruscan                 1234
Iran                     1070
Name: count, dtype: int64

In [12]:
df["Department"].value_counts()

Department
Drawings and Prints                          172630
European Sculpture and Decorative Arts        43051
Photographs                                   37459
Asian Art                                     37000
Greek and Roman Art                           33726
Costume Institute                             31652
Egyptian Art                                  27969
The American Wing                             18532
Islamic Art                                   15573
Modern and Contemporary Art                   14696
Arms and Armor                                13623
Arts of Africa, Oceania, and the Americas     12367
Medieval Art                                   7142
Ancient Near Eastern Art                       6223
Musical Instruments                            5227
European Paintings                             2626
Robert Lehman Collection                       2586
The Cloisters                                  2340
The Libraries                                   534
Name: count, dtype: int64